set(BUILD_WITH_GL3W_DEFAULT TRUE)

option(BUILD_WITH_GL3W "GL3W Enabled" ${BUILD_WITH_GL3W_DEFAULT})
message("BUILD_WITH_GL3W: ${BUILD_WITH_GL3W}")

if(BUILD_WITH_GL3W)
  set(GL3W_DIR ${THIRDPARTY_DIR}/gl3w)
  file(GLOB GL3W_CLIENT "${THIRDPARTY_DIR}/GL/*")
  file(GLOB GL3W_COMMON "${THIRDPARTY_DIR}/KHR/*")
  set(GL3W_FILES
    ${GL3W_DIR}/gl3w.c)

  add_library(gl3w STATIC ${GL3W_FILES})
endif()